package org.catrobat.catroid.common.defaultprojectcreators;

import android.content.Context;
import android.content.res.Resources;
import java.io.File;
import java.io.IOException;
import org.billthefarmer.mididriver.GeneralMidiConstants;
import org.catrobat.catroid.ProjectManager;
import org.catrobat.catroid.common.Constants;
import org.catrobat.catroid.common.LookData;
import org.catrobat.catroid.content.Project;
import org.catrobat.catroid.content.Script;
import org.catrobat.catroid.content.SingleSprite;
import org.catrobat.catroid.content.Sprite;
import org.catrobat.catroid.content.StartScript;
import org.catrobat.catroid.content.WhenScript;
import org.catrobat.catroid.content.bricks.PlaceAtBrick;
import org.catrobat.catroid.content.bricks.SetLookBrick;
import org.catrobat.catroid.content.bricks.SetSizeToBrick;
import org.catrobat.catroid.drone.jumpingsumo.JumpingSumoBrickFactory;
import org.catrobat.catroid.drone.jumpingsumo.JumpingSumoBrickFactory.JumpingSumoBricks;
import org.catrobat.catroid.generated70026.R;
import org.catrobat.catroid.io.ResourceImporter;
import org.catrobat.catroid.io.XstreamSerializer;
import org.catrobat.catroid.ui.fragment.SpriteFactory;
import org.catrobat.catroid.utils.ImageEditing;

public class JumpingSumoProjectCreator extends ProjectCreator {
    private static SpriteFactory spriteFactory = new SpriteFactory();

    public JumpingSumoProjectCreator() {
        this.defaultProjectNameResourceId = R.string.default_jumping_sumo_project_name;
    }

    public Project createDefaultProject(String projectName, Context context, boolean landscapeMode) throws IOException, IllegalArgumentException {
        String str = projectName;
        Context context2 = context;
        if (XstreamSerializer.getInstance().projectExists(str)) {
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.append("Project with name '");
            stringBuilder.append(str);
            stringBuilder.append("' already exists!");
            throw new IllegalArgumentException(stringBuilder.toString());
        }
        String backgroundName = context2.getString(R.string.add_look_drone_video);
        SetSizeToBrick setSizeBrick = new SetSizeToBrick(60.0d);
        Script whenProjectStartsScript = new StartScript();
        whenProjectStartsScript.addBrick(setSizeBrick);
        Script whenSpriteTappedScript = new WhenScript();
        Project defaultJumpingSumoProject = new Project(context2, str, true);
        File sceneDir = defaultJumpingSumoProject.getDefaultScene().getDirectory();
        defaultJumpingSumoProject.setDeviceData(context2);
        XstreamSerializer.getInstance().saveProject(defaultJumpingSumoProject);
        ProjectManager.getInstance().setProject(defaultJumpingSumoProject);
        backgroundImageScaleFactor = ImageEditing.calculateScaleFactorToScreenSize(R.drawable.drone_project_background, context2);
        Resources resources = context.getResources();
        StringBuilder stringBuilder2 = new StringBuilder();
        stringBuilder2.append(backgroundName);
        stringBuilder2.append(Constants.DEFAULT_IMAGE_EXTENSION);
        File backgroundFile = ResourceImporter.createImageFileFromResourcesInDirectory(resources, R.drawable.ic_video, sceneDir, stringBuilder2.toString(), backgroundImageScaleFactor);
        Sprite sprite = spriteFactory.newInstance(SingleSprite.class.getSimpleName(), backgroundName);
        LookData backgroundLookData = new LookData();
        backgroundLookData.setName(context2.getString(R.string.add_look_jumping_sumo_video));
        backgroundLookData.setFile(backgroundFile);
        sprite.getLookList().add(backgroundLookData);
        Sprite backgroundSprite = (Sprite) defaultJumpingSumoProject.getDefaultScene().getSpriteList().get(0);
        backgroundSprite.getLookList().add(backgroundLookData);
        Script backgroundStartScript = new StartScript();
        SetLookBrick setLookBrick = new SetLookBrick();
        setLookBrick.setLook(backgroundLookData);
        backgroundStartScript.addBrick(setLookBrick);
        backgroundSprite.addScript(backgroundStartScript);
        backgroundSprite.addScript(whenProjectStartsScript);
        backgroundSprite.addScript(whenSpriteTappedScript);
        str = context2.getString(R.string.default_jumping_sumo_project_sprites_forward);
        Resources resources2 = context.getResources();
        StringBuilder stringBuilder3 = new StringBuilder();
        stringBuilder3.append(str);
        stringBuilder3.append(Constants.DEFAULT_IMAGE_EXTENSION);
        String stringBuilder4 = stringBuilder3.toString();
        String str2 = str;
        defaultJumpingSumoProject.getDefaultScene().addSprite(createJumpingSumoSprite(str2, JumpingSumoBricks.JUMPING_SUMO_FORWARD, (int) (-350.0d / 1.63d), (int) (150.0d / 1.63d), ResourceImporter.createImageFileFromResourcesInDirectory(resources2, R.drawable.default_jumping_sumo_project_forward, sceneDir, stringBuilder4, 4610785298501913805), 1000, GeneralMidiConstants.LEAD_0_SQUARE, (byte) 0, 0.0f));
        String backwardName = context2.getString(R.string.default_jumping_sumo_project_sprites_backward);
        resources = context.getResources();
        stringBuilder2 = new StringBuilder();
        stringBuilder2.append(backwardName);
        stringBuilder2.append(Constants.DEFAULT_IMAGE_EXTENSION);
        String backwardName2 = backwardName;
        str2 = backwardName2;
        defaultJumpingSumoProject.getDefaultScene().addSprite(createJumpingSumoSprite(str2, JumpingSumoBricks.JUMPING_SUMO_BACKWARD, (int) (-350.0d / 1.63d), (int) (-150.0d / 1.63d), ResourceImporter.createImageFileFromResourcesInDirectory(resources, R.drawable.default_jumping_sumo_project_backward, sceneDir, stringBuilder2.toString(), 4610785298501913805), 1000, GeneralMidiConstants.LEAD_0_SQUARE, (byte) 0, 0.0f));
        backwardName = context2.getString(R.string.default_jumping_sumo_project_sprites_animation);
        resources = context.getResources();
        stringBuilder2 = new StringBuilder();
        stringBuilder2.append(backwardName);
        stringBuilder2.append(Constants.DEFAULT_IMAGE_EXTENSION);
        String animationName = backwardName;
        str2 = animationName;
        defaultJumpingSumoProject.getDefaultScene().addSprite(createJumpingSumoSprite(str2, JumpingSumoBricks.JUMPING_SUMO_ANIMATIONS, 0, (int) (325.0d / 1.63d), ResourceImporter.createImageFileFromResourcesInDirectory(resources, R.drawable.default_jumping_sumo_project_animations, sceneDir, stringBuilder2.toString(), 4604930618986332160L), 0, (byte) 0, (byte) 0, 0.0f));
        backwardName = context2.getString(R.string.default_jumping_sumo_project_sprites_sound);
        resources = context.getResources();
        stringBuilder2 = new StringBuilder();
        stringBuilder2.append(backwardName);
        stringBuilder2.append(Constants.DEFAULT_IMAGE_EXTENSION);
        String soundName = backwardName;
        str2 = soundName;
        defaultJumpingSumoProject.getDefaultScene().addSprite(createJumpingSumoSprite(str2, JumpingSumoBricks.JUMPING_SUMO_SOUND, (int) (250.0d / 1.63d), (int) (325.0d / 1.63d), ResourceImporter.createImageFileFromResourcesInDirectory(resources, R.drawable.default_jumping_sumo_project_sound, sceneDir, stringBuilder2.toString(), 4610785298501913805), 0, (byte) 0, (byte) 50, 0.0f));
        backwardName = context2.getString(R.string.default_jumping_sumo_project_sprites_no_sound);
        resources = context.getResources();
        stringBuilder2 = new StringBuilder();
        stringBuilder2.append(backwardName);
        stringBuilder2.append(Constants.DEFAULT_IMAGE_EXTENSION);
        String noSoundName = backwardName;
        str2 = noSoundName;
        defaultJumpingSumoProject.getDefaultScene().addSprite(createJumpingSumoSprite(str2, JumpingSumoBricks.JUMPING_SUMO_NO_SOUND, (int) (375.0d / 1.63d), (int) (325.0d / 1.63d), ResourceImporter.createImageFileFromResourcesInDirectory(resources, R.drawable.default_jumping_sumo_project_sound_off, sceneDir, stringBuilder2.toString(), 4610785298501913805), 0, (byte) 0, (byte) 0, 0.0f));
        backwardName = context2.getString(R.string.default_jumping_sumo_project_sprites_jump_long);
        resources = context.getResources();
        stringBuilder2 = new StringBuilder();
        stringBuilder2.append(backwardName);
        stringBuilder2.append(Constants.DEFAULT_IMAGE_EXTENSION);
        String jumpLongName = backwardName;
        str2 = jumpLongName;
        defaultJumpingSumoProject.getDefaultScene().addSprite(createJumpingSumoSprite(str2, JumpingSumoBricks.JUMPING_SUMO_JUMP_LONG, (int) (500.0d / 1.63d), (int) (-100.0d / 1.63d), ResourceImporter.createImageFileFromResourcesInDirectory(resources, R.drawable.default_jumping_sumo_project_jump_long, sceneDir, stringBuilder2.toString(), 4610785298501913805), 0, (byte) 0, (byte) 0, 0.0f));
        backwardName = context2.getString(R.string.default_jumping_sumo_project_sprites_jump_high);
        resources = context.getResources();
        stringBuilder2 = new StringBuilder();
        stringBuilder2.append(backwardName);
        stringBuilder2.append(Constants.DEFAULT_IMAGE_EXTENSION);
        String jumpHighName = backwardName;
        str2 = jumpHighName;
        defaultJumpingSumoProject.getDefaultScene().addSprite(createJumpingSumoSprite(str2, JumpingSumoBricks.JUMPING_SUMO_JUMP_HIGH, (int) (500.0d / 1.63d), (int) (50.0d / 1.63d), ResourceImporter.createImageFileFromResourcesInDirectory(resources, R.drawable.default_jumping_sumo_project_jump_high, sceneDir, stringBuilder2.toString(), 4610785298501913805), 0, (byte) 0, (byte) 0, 0.0f));
        backwardName = context2.getString(R.string.default_jumping_sumo_project_sprites_turn_left);
        resources = context.getResources();
        stringBuilder2 = new StringBuilder();
        stringBuilder2.append(backwardName);
        stringBuilder2.append(Constants.DEFAULT_IMAGE_EXTENSION);
        String turnLeftName = backwardName;
        str2 = turnLeftName;
        defaultJumpingSumoProject.getDefaultScene().addSprite(createJumpingSumoSprite(str2, JumpingSumoBricks.JUMPING_SUMO_ROTATE_LEFT, (int) (-500.0d / 1.63d), 0, ResourceImporter.createImageFileFromResourcesInDirectory(resources, R.drawable.default_jumping_sumo_project_left, sceneDir, stringBuilder2.toString(), 4610785298501913805), 0, GeneralMidiConstants.LEAD_0_SQUARE, (byte) 0, 90.0f));
        backwardName = context2.getString(R.string.default_jumping_sumo_project_sprites_turn_right);
        resources = context.getResources();
        stringBuilder2 = new StringBuilder();
        stringBuilder2.append(backwardName);
        stringBuilder2.append(Constants.DEFAULT_IMAGE_EXTENSION);
        String turnRightName = backwardName;
        str2 = turnRightName;
        defaultJumpingSumoProject.getDefaultScene().addSprite(createJumpingSumoSprite(str2, JumpingSumoBricks.JUMPING_SUMO_ROTATE_RIGHT, (int) (-200.0d / 1.63d), 0, ResourceImporter.createImageFileFromResourcesInDirectory(resources, R.drawable.default_jumping_sumo_project_right, sceneDir, stringBuilder2.toString(), 4610785298501913805), 0, GeneralMidiConstants.LEAD_0_SQUARE, (byte) 0, 90.0f));
        backwardName = context2.getString(R.string.default_jumping_sumo_project_sprites_flip);
        resources = context.getResources();
        stringBuilder2 = new StringBuilder();
        stringBuilder2.append(backwardName);
        stringBuilder2.append(Constants.DEFAULT_IMAGE_EXTENSION);
        String flipName = backwardName;
        str2 = flipName;
        defaultJumpingSumoProject.getDefaultScene().addSprite(createJumpingSumoSprite(str2, JumpingSumoBricks.JUMPING_SUMO_TURN, (int) (500.0d / 1.63d), (int) (-250.0d / 1.63d), ResourceImporter.createImageFileFromResourcesInDirectory(resources, R.drawable.default_jumping_sumo_project_flip, sceneDir, stringBuilder2.toString(), 4610785298501913805), 0, (byte) 0, (byte) 0, 0.0f));
        backwardName = context2.getString(R.string.default_jumping_sumo_project_sprites_picture);
        File pictureFile = context.getResources();
        stringBuilder2 = new StringBuilder();
        stringBuilder2.append(backwardName);
        stringBuilder2.append(Constants.DEFAULT_IMAGE_EXTENSION);
        String pictureName = backwardName;
        str2 = pictureName;
        defaultJumpingSumoProject.getDefaultScene().addSprite(createJumpingSumoSprite(str2, JumpingSumoBricks.JUMPING_SUMO_PICTURE, (int) (500.0d / 1.63d), (int) (325.0d / 1.63d), ResourceImporter.createImageFileFromResourcesInDirectory(pictureFile, R.drawable.default_jumping_sumo_project_camera, sceneDir, stringBuilder2.toString(), 4610785298501913805), 0, (byte) 0, (byte) 0, 0.0f));
        return defaultJumpingSumoProject;
    }

    private Sprite createJumpingSumoSprite(String spriteName, JumpingSumoBricks jumpingSumoBrick, int xPosition, int yPosition, File lookFile, int timeInMilliseconds, byte powerInPercent, byte volumeInPercent, float degree) {
        String str = spriteName;
        Sprite sprite = spriteFactory.newInstance(SingleSprite.class.getSimpleName(), str);
        Script whenSpriteTappedScript = new WhenScript();
        whenSpriteTappedScript.addBrick(JumpingSumoBrickFactory.getInstanceOfJumpingSumoBrick(jumpingSumoBrick, timeInMilliseconds, powerInPercent, volumeInPercent, degree));
        Script whenProjectStartsScript = new StartScript();
        PlaceAtBrick placeAtBrick = new PlaceAtBrick(ProjectCreator.calculateValueRelativeToScaledBackground(xPosition), ProjectCreator.calculateValueRelativeToScaledBackground(yPosition));
        SetSizeToBrick setSizeBrick = new SetSizeToBrick(40.0d);
        whenProjectStartsScript.addBrick(placeAtBrick);
        whenProjectStartsScript.addBrick(setSizeBrick);
        LookData lookData = new LookData();
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append(str);
        stringBuilder.append(" icon");
        lookData.setName(stringBuilder.toString());
        lookData.setFile(lookFile);
        sprite.getLookList().add(lookData);
        sprite.addScript(whenSpriteTappedScript);
        sprite.addScript(whenProjectStartsScript);
        return sprite;
    }
}
