package com.parrot.arsdk.arcommands;

public interface ARCommandARDrone3MediaStreamingVideoStreamModeListener {
    void onARDrone3MediaStreamingVideoStreamModeUpdate(ARCOMMANDS_ARDRONE3_MEDIASTREAMING_VIDEOSTREAMMODE_MODE_ENUM arcommands_ardrone3_mediastreaming_videostreammode_mode_enum);
}
