package com.parrot.arsdk.arcommands;

public interface ARCommandPowerupMediaRecordEventVideoEventChangedListener {
    void onPowerupMediaRecordEventVideoEventChangedUpdate(ARCOMMANDS_POWERUP_MEDIARECORDEVENT_VIDEOEVENTCHANGED_EVENT_ENUM arcommands_powerup_mediarecordevent_videoeventchanged_event_enum, ARCOMMANDS_POWERUP_MEDIARECORDEVENT_VIDEOEVENTCHANGED_ERROR_ENUM arcommands_powerup_mediarecordevent_videoeventchanged_error_enum);
}
