package com.parrot.arsdk.arcommands;

public interface ARCommandARDrone3PilotingStateLandingStateChangedListener {
    void onARDrone3PilotingStateLandingStateChangedUpdate(ARCOMMANDS_ARDRONE3_PILOTINGSTATE_LANDINGSTATECHANGED_STATE_ENUM arcommands_ardrone3_pilotingstate_landingstatechanged_state_enum);
}
