package com.parrot.arsdk.arcommands;

public interface ARCommandPowerupPilotingStateMotorModeChangedListener {
    void onPowerupPilotingStateMotorModeChangedUpdate(ARCOMMANDS_POWERUP_PILOTINGSTATE_MOTORMODECHANGED_MODE_ENUM arcommands_powerup_pilotingstate_motormodechanged_mode_enum);
}
