package com.parrot.arsdk.arcommands;

public interface ARCommandARDrone3PictureSettingsVideoResolutionsListener {
    void onARDrone3PictureSettingsVideoResolutionsUpdate(ARCOMMANDS_ARDRONE3_PICTURESETTINGS_VIDEORESOLUTIONS_TYPE_ENUM arcommands_ardrone3_picturesettings_videoresolutions_type_enum);
}
